# .github/workflows/main.yml
name: Run Jest Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        # run: npm run ghworkflowtest -- --ci --reporters=default --reporters=jest-junit

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: reports/junit/junit.xml

      - name: update Airtable
        if: always()
        run: node ./.scripts/main.js TS ${{github.actor}} https://github.com/${{github.repository}}
